### ISSUE TITLE
Feature request: More color formats

### ISSUE THREAD

**Issue by hugolundin** [sindresorhus/System-Color-Picker#2]
As an iOS developer, I often need colors formatted according to the UIColor / SwiftUI.Color initializer. Support for that would be great! 😊

**Comment by sindresorhus** [comment]
I considered this, but the best practice is to use [Asset Catalog for colors](https://devblog.xero.com/managing-ui-colours-with-ios-11-asset-catalogs-16500ba48205) instead of hard-coding the values in code.

If you really want to hard-code colors, the https://bjango.com/mac/skalacolor/ color picker plugin supports this.

**Comment by hugolundin** [comment]
> I considered this, but the best practice is to use [Asset Catalog for colors](https://devblog.xero.com/managing-ui-colours-with-ios-11-asset-catalogs-16500ba48205) instead of hard-coding the values in code.

True 😅

> If you really want to hard-code colors, the https://bjango.com/mac/skalacolor/ color picker plugin supports this.

Thanks for the suggestion! I didn't actually know that the built-in color supported plugins.
